### ISSUE TITLE
Weird unread message behaviour

### ISSUE THREAD

**Issue by justabaka** [3v1n0/telegram-snap#10]
Messages are not marked as read after viewing them, but only after sending a message / saving a draft. Context menu option (Mark as read) works. Channel messages are always shown as unread unless you use the context menu option.

Maybe it's a some kind of an upstream bug which requires rolling the vcs revision back until they fix it.

Client version:
```
Name                  Version              Rev    Tracking
telegram-desktop      1.5.15-112-gef682e7  581    edge
```

P.S. Switching to stable (1.5.15 R551) "resolves" the issue.

**Comment by 3v1n0** [comment]
Please, report the issue at the actual project: https://github.com/telegramdesktop/tdesktop
