### ISSUE TITLE
Input method support

### ISSUE THREAD

**Issue by extraymond** [3v1n0/telegram-snap#3]
Hi! Thx for the snap.
It would be more awesome if input method support is landed, for example ibus or fcitx support.

**Comment by favadi** [comment]
I can use Ibus on other snap packages like Skype, Mattermost without any problem. What should be done to enable input method support for Telegram?

**Comment by anthonywong** [comment]
The reason why ibus or fcitx does not work is because `QT_IM_MODULE` is set to `xim` explicitly. I've talked to Marco and the reason doing so is to make compose key works. This looks like a workaround to me though and I guess there is something else to be fixed to make compose key works.
