### ISSUE TITLE
Default folders created after installing via Snap

### ISSUE THREAD

**Issue by mmartinortiz** [3v1n0/telegram-snap#4]
After installing Telegram snap I got empty default folders in my $HOME folder. I checked the time of the folder creation and looked for matches on the system log. My `$HOME/.config/user-dirs.locale` is set to `es_ES`, and `$HOME/.config/user-dirs.dirs` have the right strings in my language. Here are some details:

**ll -l $HOME**
```bash
drwxr-xr-x  2 user user  4096 mar 28 19:49 Desktop/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Documents/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Downloads/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Music/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Pictures/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Public/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Templates/
drwxr-xr-x  2 user user  4096 mar 28 19:49 Videos/
```

**/var/log/kern.log**
```bash
/var/log/kern.log.1:Mar 28 19:49:09 juno kernel: [77540.613939] audit: type=1400 audit(1522259349.149:110): apparmor="DENIED" operation="open" profile="snap.telegram-desktop.telegram-desktop" name="/etc/xdg/QtProject/qtlogging.ini" pid=14831 comm="Telegram" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

It seems that `/etc/xdg/user-dirs.defaults` is used instead `$HOME/.config/user-dirs.dirs` when installing the snap

**Comment by 3v1n0** [comment]
This is actually an issue related to https://github.com/ubuntu/snapcraft-desktop-helpers/issues/92 and there's a PR already in progress for fixing this.

See: https://github.com/ubuntu/snapcraft-desktop-helpers/pull/103
