### ISSUE TITLE
Open dialog incoherent and without icons and permissions issues on Kubuntu 18.04

### ISSUE THREAD

**Issue by emanuc** [3v1n0/telegram-snap#8]
As a title, I tried to save a video on the Telegram snap, in addition to the fact that I can not save it on "downloaded" that I have moved by default to: "/media/user/data1/downloaded", as screenshot the theme of dialog is inconsistent and without icons.

> emanu@emanuc:~$ snap version
> snap    2.32.9+18.04
> snapd   2.32.9+18.04
> series  16
> ubuntu  18.04
> kernel  4.15.0-22-generic

> emanu@emanuc:~$ snap info telegram-desktop
> name:      telegram-desktop
> summary:   Official desktop client for the Telegram messenger
> publisher: 3v1n0
> contact:   https://github.com/3v1n0/telegram-snap/issues
> license:   unknown
> description: |
>   Telegram is a popular messaging protocol with encryption and security as
>   its key focus.
>   
>   Fast and secure desktop app, perfectly synced with your mobile phone.
> commands:
>   - telegram-desktop
> snap-id:   jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
> tracking:  stable
> refreshed: 2018-04-09T17:56:46+02:00
> installed:   1.2.17                  (142) 100MB -
> channels:                                  
>   stable:    1.2.17                  (142) 100MB -
>   candidate: ↑                                   
>   beta:      1.2.20-alpha            (178) 100MB -
>   edge:      1.2.21-alpha+gitc43dcf0 (180) 100MB -

![screenshot_20180524_142052](https://user-images.githubusercontent.com/27281121/40485674-78d90d2a-5f5f-11e8-9bc8-131e86c58bd3.png)

**Comment by 3v1n0** [comment]
That theming isn't managed by the snap itself.

As per the permission, it needs to be manually allowed with `sudo snap connect telegram-desktop:removable-media`

It's only fixed in the `edge` and `beta` channels though (`snap refresh --edge telegram-desktop`)
